spring:
  application:
    name: order-service
  
  profiles:
    active: dev  # Use 'dev' profile by default (enables demo user seeding)
  
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: order_user
    password: order_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    # Admin config for auto-creating topics
    admin:
      properties:
        bootstrap.servers: localhost:9092

server:
  port: 8081

# JWT Configuration
jwt:
  secret: mySecretKeyForJWTtokenGenerationThatIsAtLeast256BitsLongForHS256Algorithm
  expiration: 900000  # 15 minutes in milliseconds

logging:
  level:
    com.streamcart.order: DEBUG
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true